[project]
name = "VideoResolver"
version = "1.2.33"
description = "GsCore 链接分享视频、图片和音乐解析插件"
requires-python = ">=3.11,<4.0"
readme = "README.md"
license = { text = "MulanPSL2" }
dependencies = [
    "aiofiles>=24.1.0",
    "httpx>=0.27.0",
    "bilibili-api-python>=16.2.0",
    "PyExecJS>=1.5.1",
    "yt-dlp>=2024.11.18",
    "pytakumi>=0.1.0",
]

[project.urls]
Homepage = "https://github.com/bvzrays/VideoResolver"
Repository = "https://github.com/bvzrays/VideoResolver"
